name: Release

permissions: {}

on:
  push:
    branches:
      - main
    paths:
      - package.json

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  check:
    name: Check version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      version_changed: ${{ steps.version.outputs.changed }}
      is_pre_release: ${{ steps.check_pre_release.outputs.is_pre_release }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2

      - name: Check version changes
        uses: EndBug/version-check@5102328418c0130d66ca712d755c303e93368ce2 # v2.1.7
        id: version
        with:
          diff-search: true
          file-name: package.json

      - name: Check if pre-release
        id: check_pre_release
        if: steps.version.outputs.changed == 'true'
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ "$COMMIT_MSG" == *"[pre-release]"* ]]; then
            echo "is_pre_release=true" >> $GITHUB_OUTPUT
          else
            echo "is_pre_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Print version
        if: steps.version.outputs.changed == 'true'
        run: |
          echo "Version change found! New version: ${{ steps.version.outputs.version }}"
          echo "Pre-release: ${{ steps.check_pre_release.outputs.is_pre_release }}"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.version_changed == 'true'
    steps:
      - uses: taiki-e/checkout-action@3ab630d442e198ebb0ca30872832406ca01c46eb # v1.4.0

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Compile
        run: pnpm run compile

      - name: Package
        run: pnpm run ${{ needs.check.outputs.is_pre_release == 'true' && 'package:pre-release' || 'package' }}

      - name: Upload artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          if-no-files-found: error
          name: vsix
          path: ./oxc_language_server.vsix

  publish-vsce:
    name: Publish to Microsoft Marketplace
    runs-on: ubuntu-latest
    needs: [check, build]
    permissions:
      contents: write
    steps:
      - uses: taiki-e/checkout-action@3ab630d442e198ebb0ca30872832406ca01c46eb # v1.4.0

      - name: Download artifact
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: vsix

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Publish to Microsoft Marketplace
        run: pnpm exec vsce publish ${{ needs.check.outputs.is_pre_release == 'true' && '--pre-release' || '' }} --packagePath oxc_language_server.vsix
        env:
          VSCE_PAT: ${{ secrets.VSCE_PERSONAL_ACCESS_TOKEN }}

  publish-ovsx:
    name: Publish to Open VSX Registry
    runs-on: ubuntu-latest
    needs: [check, build]
    permissions:
      contents: write
    steps:
      - uses: taiki-e/checkout-action@3ab630d442e198ebb0ca30872832406ca01c46eb # v1.4.0

      - name: Download artifact
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: vsix

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Publish to Open VSX Registry
        run: pnpm exec ovsx publish ${{ needs.check.outputs.is_pre_release == 'true' && '--pre-release' || '' }} --packagePath oxc_language_server.vsix
        env:
          OVSX_PAT: ${{ secrets.OPEN_VSX_TOKEN }}

  github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [check, build, publish-vsce, publish-ovsx]
    permissions:
      contents: write
    steps:
      - uses: taiki-e/checkout-action@3ab630d442e198ebb0ca30872832406ca01c46eb # v1.4.0

      - name: Create GitHub Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          draft: false
          prerelease: ${{ needs.check.outputs.is_pre_release == 'true' }}
          name: v${{ needs.check.outputs.version }}
          tag_name: v${{ needs.check.outputs.version }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
